### ISSUE TITLE
Subnet address search with zero results raises incorrect exception

### ISSUE THREAD

**Issue by alexbb** [codeaffen/pyhpipam#51]
**Describe the bug**
When searching for addresses in an empty subnet a generic `PHPyPAMException` is raised instead of `PHPyPAMEntityNotFoundException`.

**To Reproduce**
1. In phpIPAM, create a new subnet with no address entries.
2. Search the subnet for addresses via phpypam: `IPAM_API.get_entity(controller='subnets', controller_path=subnet['id']+'/addresses/')`
3. PHPyPAMException is raised with message "No addresses found"

**Expected behavior**
`PHPyPAMEntityNotFoundException` should be raised instead.

**Versions:**

- python: 3.8.10
- phpypam: 1.0.2

**Additional context**
None.

**Comment by cmeissner** [comment]
Thank you @alexbb for reporting this issue. I started to dig a bit to found the root cause. For that I request the api of my test setup directly via `curl`. 

```
curl -s -X GET -H "token: my-very-secret-token" https://phpipam.example.com/api/myappid/subnets/73/addresses/ | jq
{
  "code": 200,
  "success": false,
  "message": "No addresses found",
  "time": 0.005
}
```

The problem is here that the request reports `"success": false`. 

> One can argue whether this is really an issue because "no addresses" can be valid result. But this shouldn't be the place to discuss this.

Our `_query()`-code does the following ([phpypam.core.api](https://github.com/codeaffen/phpypam/blob/e7cc62e5a32f18045b93a9a2ae978d42da1b17f6/phpypam/core/api.py#L123-L124)).
In [phpypam.core.exeptions](https://github.com/codeaffen/phpypam/blob/e7cc62e5a32f18045b93a9a2ae978d42da1b17f6/phpypam/core/exceptions.py#L38-L39) we raise `PHPyPAMEntityNotFoundException` only if the messe is in [_NOT_FOUND_MESSAGES](https://github.com/codeaffen/phpypam/blob/e7cc62e5a32f18045b93a9a2ae978d42da1b17f6/phpypam/core/exceptions.py#L10-L19).

So a simple solution is to simply add `No addresses found` to that list. After that the correct exception will be raised.

Now I'll be keen to ask if you are willingly to fix it and open a PR?

**Comment by alexbb** [comment]
@cmeissner I came to the same conclusion, adding the string to `_NOT_FOUND_MESSAGES` does give the expected behavior. I started work on a PR yesterday but haven't had time to fully understand the test setup yet so I can add a test case. I may have time for that tomorrow or next week.

**Comment by cmeissner** [comment]
@alexbb  great to hear. If you need some help you can use our IRC channels #codeaffen and #codeaffen-dev on libera.chat network to get in touch, if you want. 
Alternatively we also offers the project discussions on github.
